version: '3.7'
services:
    session_cache:
        image: redis:6.2.5-alpine
        container_name: tripsit_api_session_store
        restart: always
        ports:
            - 6379:6379/tcp
        volumes:
            - 'tripsit_session_data:/data'
volumes:
    tripsit_session_data:
        name: tripsit_session_redis_store
        driver: local
